name: Build clang-latest

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build clang
        shell: bash
        run: |
          git clone https://github.com/llvm/llvm-project.git
          cd llvm-project
          mkdir build && cd build

          cmake -G Ninja ../llvm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
            -DLLVM_TARGETS_TO_BUILD="X86;ARM" \
            -DCMAKE_INSTALL_PREFIX="$PWD/install" \
            -DLLVM_ENABLE_ASSERTIONS=ON
